### ISSUE TITLE
Models as universalObjectCrate

### ISSUE THREAD

**Issue by m-vo** [contao/phpstan#7]
**Description**  
I keep adding the Contao model base class to the list of `universalObjectCrates` in my applications so that phpstan does not complain about the magic property access (`$model->some_property`). As discussed briefly on slack this might be something this extension could perhaps provide out of the box - wdyt?

see https://github.com/phpstan/phpstan#universal-object-crates

**Example**  
```yml
parameters:
  universalObjectCratesClasses:
    - Contao\Model
```
